export const cardData = [{
    id: 0,
    title: 'tornado',
    image: 'w2Sx1i7rE8dfdyDSAb'
  }, {
    id: 1,
    title: 'volcano',
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/codeigniter/codeigniter-plain.svg'
  }, {
    id: 2,
    title: 'blizzard',
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/coffeescript/coffeescript-original.svg'
  }, {
    id: 3,
    title: 'blizzard',
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/coffeescript/coffeescript-original.svg'
  }, {
    id: 4,
    title: 'blizzard',
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/coffeescript/coffeescript-original.svg'
  }, {
    id: 5,
    title: 'blizzard',
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/coffeescript/coffeescript-original.svg'
  }, {
    id: 6,
    title: 'blizzard',
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/coffeescript/coffeescript-original.svg'
  }, {
    id: 7,
    title: 'blizzard',
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/coffeescript/coffeescript-original.svg'
  }, {
    id: 8,
    title: 'blizzard',
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/coffeescript/coffeescript-original.svg'
  }, {
    id: 9,
    title: 'blizzard',
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/coffeescript/coffeescript-original.svg'
  }, {
    id: 10,
    title: 'blizzard',
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/coffeescript/coffeescript-original.svg'
  }, {
    id: 11,
    title: 'blizzard',
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/coffeescript/coffeescript-original.svg'
  }
];