export const cardData = [{
    id: 0,
    title: 'tornado',
    gifId: 'w2Sx1i7rE8dfdyDSAb'
  }, {
    id: 1,
    title: 'volcano',
    gifId: 'r5gHt2TCIiHK0'
  }, {
    id: 2,
    title: 'blizzard',
    gifId: 'Xi2Xu0MejhsUo'
  }, {
    id: 3,
    title: 'hurricane',
    gifId: 'HmTLatwLWpTQk'
  }, {
    id: 4,
    title: 'tsunami',
    gifId: 'WbH025dAr6so'
  }, {
    id: 5,
    title: 'wildfire',
    gifId: 'NWpDqhCzmRkWh2os4U'
  }, {
    id: 6,
    title: 'earthquake',
    gifId: 'l0HlAJti7DgiZ1H9u'
  }, {
    id: 7,
    title: 'drought',
    gifId: 'WsvHRUQqYb5qpp33SR'
  }, {
    id: 8,
    title: 'flood',
    gifId: 'KYWdVhA36WuRLyiy9H'
  }, {
    id: 9,
    title: 'avalanche',
    gifId: 'ZTjQgJGDiuJZS'
  }, {
    id: 10,
    title: 'dust storm',
    gifId: 'lPNqO3u4p1gewVI4VJ'
  }, {
    id: 11,
    title: 'sinkhole',
    gifId: 'I3QOE8SlXfcju'
  }
];